### ISSUE TITLE
README changes (suggested)

### ISSUE THREAD

**Issue by cnissenbaum2019** [zhanglydia/TeammaeT#3]
In Recursive Abstraction:
1. The [our] conventional way of starting the RA is with "When asked to _______ , the RA can..." I feel that this would improve your Recursive Abstraction. 
2. Rather than "given starting moves," you could say: "given a new maze with a new explorer position."

In English or Pseudocode Description of Algorithm:
1. For specification sake, you may want to define "legal moves" in lines [2] and [3].
2. For my sake, explain the process implied by "recurse" in line [3].

**Comment by dkeriazisStuy** [comment]
Thank you for this valuable feedback. I will address your points and the changes that have been made in order to be compliant (or defiant) with them:

In `Recursive Abstraction`:
Your points here have been taken as you have suggested them
The `Recursive Abstraction` section now reads:
>## Recursive Abstraction
>
>When asked to return the boolean value of the statement "the maze is navigable, having a legal travel path from current position to existing treasure",
the recursive abstraction can return the value of said statement with an explorer in a new position.

In `English or Pseudocode Description of Algorithm`:
This section has been overhauled to be more correct and more clear. These changes include now using the term "cardinal direction" instead of the admittedly-vague and incorrect "legal moves". 
However, one change that has _not_ been made is removing or clarifying the term "recurse". One reason for this is that "recurse" is a word in the English language:

From [https://en.wiktionary.org/wiki/recurse#Verb](https://en.wiktionary.org/wiki/recurse#Verb),
>1. (intransitive, computing) To execute a procedure recursively.

The `English or Pseudocode Description of Algorithm` section now reads:
>## English or Pseudocode Description of Algorithm
>
>    ```
>    If current position contains treasure, return true
>    If current position contains a wall, revert to snapshot
>    For each cardinal direction:
>        Update snapshot to match current state
>        Drop a wall
>        Move the explorer in that direction
>        Recurse
>    Return false
>    ```

If you disagree with any of these changes or wish for further ones to be made, please respond to this issue. I am leaving it open as I am not quite yet satisfied with the README and am open to more discussion on its contents.

**Comment by zhanglydia** [comment]
Does update snapshot go inside or outside the loop? Since we update it before we move explorer and drop the wall, all four snapshots would capture the same thing.

**Comment by dkeriazisStuy** [comment]
Good point, the way this is written is inefficient. Updated to match this recommendation.
